# Generated by Django 4.2.1 on 2023-05-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInOutDBView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("doc_type", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=9),
                ),
            ],
            options={
                "verbose_name": "Product In Out View",
                "verbose_name_plural": "Product In Out View",
                "db_table": "product_in_out_view",
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """
                    create or replace view product_in_out_view as
                    select id, date,  'sale' as doc_type, product_id,quantity , price, value from sales_sale
                    union all
                    select id , date, 'purchase' as doc_type , quantity , product_id, price, value from purchase_purchase 
                    """
        ),
    ]
