# Generated by Django 4.2.1 on 2023-05-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
